version: "3.0"

services:
    eduard-ipc127e:
        image: eduartrobotik/eduard-ipc127e:0.3.2
        container_name: eduard-ipcbot-0.3.2
        user: user
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=eduard/red
        network_mode: "host"
#        networks:
#            - multi-robot
#            - robot-eduard
        devices:
            - '/dev:/dev'

    eduard-robot-control:
        image: eduartrobotik/eduard-robot-control-ipcbot:0.3.1
        container_name: eduard-robot-control-ipcbot-0.3.1
        user: user
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=eduard/red
        network_mode: "host"
#        networks:
#            - multi-robot
#            - robot-eduard
        devices:
            - '/dev:/dev'
        volumes:
            - '/dev:/dev'

networks:
    multi-robot:
        name: "multi-robot"
        external: true
    robot-eduard:
        name: "robot-eduard"
