/**:
  ros__parameters:
    enable_collision_avoidance: false
    
    imu:
      raw_data_mode: false
      tf_frame_rotated: base_link

    # motor_a:
    motor_a/control_frequency: 16000
    motor_a/encoder_inverted: false
    motor_a/encoder_ratio: 64.0
    motor_a/gear_ratio: 50.0
    motor_a/max_rpm: 100.0
    motor_a/pid/kd: 2.0
    motor_a/pid/ki: 10.0
    motor_a/pid/kp: 0.0
    motor_a/weight_low_pass_encoder: 0.3
    motor_a/weight_low_pass_set_point: 0.2

    # motor_b:
    motor_b/control_frequency: 16000
    motor_b/encoder_inverted: false
    motor_b/encoder_ratio: 64.0
    motor_b/gear_ratio: 50.0
    motor_b/max_rpm: 100.0
    motor_b/pid/kd: 2.0
    motor_b/pid/ki: 10.0
    motor_b/pid/kp: 0.0
    motor_b/weight_low_pass_encoder: 0.3
    motor_b/weight_low_pass_set_point: 0.2

    # motor_c:
    motor_c/control_frequency: 16000
    motor_c/encoder_inverted: false
    motor_c/encoder_ratio: 64.0
    motor_c/gear_ratio: 50.0
    motor_c/max_rpm: 100.0
    motor_c/pid/kd: 2.0
    motor_c/pid/ki: 10.0
    motor_c/pid/kp: 0.0
    motor_c/weight_low_pass_encoder: 0.3
    motor_c/weight_low_pass_set_point: 0.2

    # motor_d:  
    motor_d/control_frequency: 16000
    motor_d/encoder_inverted: false
    motor_d/encoder_ratio: 64.0
    motor_d/gear_ratio: 50.0
    motor_d/max_rpm: 100.0
    motor_d/pid/kd: 2.0
    motor_d/pid/ki: 10.0
    motor_d/pid/kp: 0.0
    motor_d/weight_low_pass_encoder: 0.3
    motor_d/weight_low_pass_set_point: 0.2

    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable

    range/front/left/field_of_view: 0.1745329201221466
    range/front/left/range_max: 5.0
    range/front/left/range_min: 0.009999999776482582
    range/front/right/field_of_view: 0.1745329201221466
    range/front/right/range_max: 5.0
    range/front/right/range_min: 0.009999999776482582
    range/rear/left/field_of_view: 0.1745329201221466
    range/rear/left/range_max: 5.0
    range/rear/left/range_min: 0.009999999776482582
    range/rear/right/field_of_view: 0.1745329201221466
    range/rear/right/range_max: 5.0
    range/rear/right/range_min: 0.009999999776482582
    tf_base_frame: base_link
    use_sim_time: false
