/**:
  ros__parameters:
    enable_collision_avoidance: true
    tf_base_frame: base_link
    tf_footprint_frame: base_footprint
    use_sim_time: false

    imu:
      fusion_weight: 0.005
      mounting_orientation:
        pitch: 0.0
        roll: 0.0
        yaw: 0.0 
      raw_data_mode: false
      tf_frame_rotated: base_link

    motor_a:
      control_frequency: 16000
      encoder_inverted: true
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      max_rpm: 140.0
      pid/kd: 0.0
      pid/ki: 7.0
      pid/kp: 0.5
      weight_low_pass_encoder: 0.8
      weight_low_pass_set_point: 0.8

    motor_b:  
      control_frequency: 16000
      encoder_inverted: true      
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      max_rpm: 140.0
      pid/kd: 0.0
      pid/ki: 7.0
      pid/kp: 0.5
      weight_low_pass_encoder: 0.8
      weight_low_pass_set_point: 0.8

    motor_c:  
      control_frequency: 16000
      encoder_inverted: true
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      max_rpm: 140.0
      pid/kd: 0.0
      pid/ki: 7.0
      pid/kp: 0.5
      weight_low_pass_encoder: 0.8
      weight_low_pass_set_point: 0.8

    motor_d:
      control_frequency: 16000
      encoder_inverted: true      
      encoder_ratio: 2048.0
      gear_ratio: 89.0
      max_rpm: 140.0
      pid/kd: 0.0
      pid/ki: 7.0
      pid/kp: 0.5
      weight_low_pass_encoder: 0.8
      weight_low_pass_set_point: 0.8

    range:  
      front:
        left:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.009999999776482582
        
        right:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.009999999776482582

      rear:    
        left:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.009999999776482582

        right:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.009999999776482582

    skid:
      length:
        x: 0.25
        y: 0.3199999928474426
      wheel_diameter: 0.17000000178813934

    mecanum:
      length:
        x: 0.25
        y: 0.36000001430511475
      wheel_diameter: 0.10000000149011612
      