/IotBot:
  ros__parameters:
    enable_collision_avoidance: false
    tf_base_frame: base_link
    use_sim_time: false

    imu:
      raw_data_mode: false
      tf_frame_rotated: base_link

    motor_a:
      control_frequency: 16000
      encoder_ratio: 2048.0
      gear_ratio: 70.0
      max_rpm: 140.0
      pid/kd: 0.0
      pid/ki: 5.0
      pid/kp: 0.5
      weight_low_pass_encoder: 0.30000001192092896
      weight_low_pass_set_point: 0.20000000298023224

    motor_b:  
      control_frequency: 16000
      encoder_ratio: 2048.0
      gear_ratio: 70.0
      max_rpm: 140.0
      pid/kd: 0.0
      pid/ki: 5.0
      pid/kp: 0.5
      weight_low_pass_encoder: 0.30000001192092896
      weight_low_pass_set_point: 0.20000000298023224

    motor_c:  
      control_frequency: 16000
      encoder_ratio: 2048.0
      gear_ratio: 70.0
      max_rpm: 140.0
      pid/kd: 0.0
      pid/ki: 5.0
      pid/kp: 0.5
      weight_low_pass_encoder: 0.30000001192092896
      weight_low_pass_set_point: 0.20000000298023224

    motor_d:
      control_frequency: 16000
      encoder_ratio: 2048.0
      gear_ratio: 70.0
      max_rpm: 140.0
      pid/kd: 0.0
      pid/ki: 5.0
      pid/kp: 0.5
      weight_low_pass_encoder: 0.30000001192092896
      weight_low_pass_set_point: 0.20000000298023224

    range:  
      front:
        left:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.009999999776482582
        
        right:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.009999999776482582

      rear:    
        left:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.009999999776482582

        right:
          field_of_view: 0.1745329201221466
          range_max: 5.0
          range_min: 0.009999999776482582
