/ethernet_gateway_flex_bot:
  ros__parameters:
    collision_avoidance/distance_reduce_velocity: 0.4000000059604645
    collision_avoidance/distance_velocity_zero: 0.05000000074505806
    collision_avoidance/enable: true
    mecanum/length/x: 0.25
    mecanum/length/y: 0.36000001430511475
    mecanum/wheel_diameter: 0.10000000149011612
    motor_a/control_frequency: 16000
    motor_a/encoder_inverted: true
    motor_a/encoder_ratio: 64.0
    motor_a/gear_ratio: 100.0
    motor_a/inverted: false
    motor_a/max_rpm: 100.0
    motor_a/pid/kd: 0.0
    motor_a/pid/ki: 5.0
    motor_a/pid/kp: 0.5
    motor_a/weight_low_pass_encoder: 0.30000001192092896
    motor_a/weight_low_pass_set_point: 0.20000000298023224
    motor_b/control_frequency: 16000
    motor_b/encoder_inverted: true
    motor_b/encoder_ratio: 64.0
    motor_b/gear_ratio: 100.0
    motor_b/inverted: false
    motor_b/max_rpm: 100.0
    motor_b/pid/kd: 0.0
    motor_b/pid/ki: 5.0
    motor_b/pid/kp: 0.5
    motor_b/weight_low_pass_encoder: 0.30000001192092896
    motor_b/weight_low_pass_set_point: 0.20000000298023224
    motor_c/control_frequency: 16000
    motor_c/encoder_inverted: true
    motor_c/encoder_ratio: 64.0
    motor_c/gear_ratio: 100.0
    motor_c/inverted: false
    motor_c/max_rpm: 100.0
    motor_c/pid/kd: 0.0
    motor_c/pid/ki: 5.0
    motor_c/pid/kp: 0.5
    motor_c/weight_low_pass_encoder: 0.30000001192092896
    motor_c/weight_low_pass_set_point: 0.20000000298023224
    motor_d/control_frequency: 16000
    motor_d/encoder_inverted: true
    motor_d/encoder_ratio: 64.0
    motor_d/gear_ratio: 100.0
    motor_d/inverted: false
    motor_d/max_rpm: 100.0
    motor_d/pid/kd: 0.0
    motor_d/pid/ki: 5.0
    motor_d/pid/kp: 0.5
    motor_d/weight_low_pass_encoder: 0.30000001192092896
    motor_d/weight_low_pass_set_point: 0.20000000298023224
    motor_e/control_frequency: 16000
    motor_e/encoder_inverted: true
    motor_e/encoder_ratio: 64.0
    motor_e/gear_ratio: 100.0
    motor_e/inverted: false
    motor_e/max_rpm: 100.0
    motor_e/pid/kd: 0.0
    motor_e/pid/ki: 5.0
    motor_e/pid/kp: 0.5
    motor_e/weight_low_pass_encoder: 0.30000001192092896
    motor_e/weight_low_pass_set_point: 0.20000000298023224
    motor_f/control_frequency: 16000
    motor_f/encoder_inverted: true
    motor_f/encoder_ratio: 64.0
    motor_f/gear_ratio: 100.0
    motor_f/inverted: false
    motor_f/max_rpm: 100.0
    motor_f/pid/kd: 0.0
    motor_f/pid/ki: 5.0
    motor_f/pid/kp: 0.5
    motor_f/weight_low_pass_encoder: 0.30000001192092896
    motor_f/weight_low_pass_set_point: 0.20000000298023224
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
      /tf:
        publisher:
          depth: 100
          durability: volatile
          history: keep_last
          reliability: reliable
    skid/length/x: 0.25
    skid/length/y: 0.3199999928474426
    skid/wheel_diameter: 0.17000000178813934
    tf_base_frame: base_link
    tf_footprint_frame: base_footprint
    use_sim_time: false
