version: "3.0"

services:
    eduard-iot2050:
        image: eduartrobotik/eduard-iotbot:0.3.2
        container_name: eduard-iotbot-0.3.2
        user: root
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=eduard/red
        network_mode: "host"
        command: bash -c 'cd /home/user/ros/launch_content; ros2 launch eduard-iot2050.launch.py'
        volumes:
            - './launch_content:/home/user/ros/launch_content:r'
        devices:
            - '/dev:/dev'
        group_add:
            - dialout

    eduard-robot-control:
        image: eduartrobotik/eduard-robot-control-iotbot:0.3.1
        container_name: eduard-robot-control-iotbot-0.3.1
        user: root
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=eduard/red
        network_mode: "host"
        devices:
            - '/dev:/dev'
        volumes:
            - '/dev:/dev'

