version: "2.4"

services:
    eduard-ipc127e:
        build: ../ipc127e
        image: eduard-ipc127e-ie-app:0.2.0
        container_name: eduard-ipc127e-ie-app-0.2.0
        restart: on-failure
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=eduard/red
        networks:
            - proxy-redirect
        volumes:
            - './publish/:/publish/'
            - './cfg-data/:/cfg-data/'
        devices:
            - '/dev:/dev'
        ports:
            - "1234:1234/udp"
#            - "7650:65535/udp"

networks:
    proxy-redirect:
        external: true
